/** Browser smoke test with explicit API fixtures. No provider requests are made. */
import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const disabledCostGates=process.env.FRONTEND_COST_GATES==='false';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const project={id:'11111111-1111-4111-8111-111111111111',title:'雾港来信 · 测试项目'};
const conversation={id:'22222222-2222-4222-8222-222222222222',project_id:project.id,title:'创作主会话'};
const task={id:'33333333-3333-4333-8333-333333333333',record_type:'task',conversation_id:conversation.id,state:'running',scope:{stage:2,description:'原作分析'},current_run_id:'44444444-4444-4444-8444-444444444444',row_version:1,created_at:'2026-09-21T05:00:00Z'};
const run={id:task.current_run_id,task_id:task.id,state:'running',row_version:1};
const artifact={id:'55555555-5555-4555-8555-555555555555',record_type:'artifact',artifact_kind:'source_analysis',latest_version:2,current_effective_version:1};
const record={id:'66666666-6666-4666-8666-666666666666',record_type:'model_call',state:'failed',error:{code:'RateLimitError',message:'已保存的模型调用失败',details:{http_status:429},retryable:false},context_snapshot_id:'77777777-7777-4777-8777-777777777777',created_at:'2026-09-21T05:00:00Z',usage:{input_tokens:4000,output_tokens:2500,reasoning_tokens:1000,reported_cost:null,estimated_cost:{amount:'0.125',currency:'USD'}},api_key:'DO-NOT-RENDER-THIS'};
const config={values:JSON.parse(await readFile(path.join(root,'docs/context/defaults.json'),'utf8')),schemas:{'test.schema':{type:'object',properties:{title:{type:'string',description:'标题'}},required:['title']}},registry:{models:{'gpt-5.6-sol':{context_window:1050000,max_output_tokens:128000,reasoning_efforts:['none','low','medium','high','xhigh','max']},'gpt-5.6-luna':{context_window:1050000,max_output_tokens:128000,reasoning_efforts:['none','low','medium','high','xhigh','max']},'gpt-5-mini':{context_window:400000,max_output_tokens:128000,reasoning_efforts:['minimal','low','medium','high']},'gpt-5-nano':{context_window:400000,max_output_tokens:128000,reasoning_efforts:['minimal','low','medium','high']}}},versions:[]};
config.values.task={max_active_seconds:3600,max_cost:{amount:'20',currency:'USD'}};
const requests=[];let projects=[project];let history=[{id:'88888888-8888-4888-8888-888888888888',record_type:'history_record',role:'assistant',visibility:'conversation',sequence:1,created_at:'2026-09-21T05:00:00Z',content:{storage:'inline_text',text:'已保存原作。我们先来确认故事中必须保留的人物关系。'}},{id:'88888888-8888-4888-8888-888888888889',record_type:'history_record',role:'assistant',visibility:'conversation',sequence:2,created_at:'2026-09-21T05:01:00Z',content:{storage:'inline_text',text:'Step2 已生成草稿 v1，请查看后确认，或提出具体修改。'},display_text:'Step 2 · 原作分析（v1）\n\n故事前提：雾港中的兄妹寻找真相。\n\n请确认以上结果，或直接提出需要修改的内容。'}];
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://127.0.0.1');if(!url.pathname.startsWith('/api/')){const file=url.pathname==='/'?'index.html':url.pathname.replace('/static/','');try{const body=await readFile(path.join(root,'branch_agent/static',file));res.setHeader('Content-Type',file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':'text/javascript');res.end(body);}catch{res.statusCode=404;res.end();}return;}if(url.pathname.endsWith('/events')){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache'});res.write(': fixture\n\n');return;}let raw='';for await(const b of req)raw+=b;const body=raw?JSON.parse(raw):null;requests.push({url:url.pathname,method:req.method,body,headers:req.headers});let data={};const suffix=url.pathname.replace('/api/branch-agent/v1','');if(suffix==='/auth/me')data={account_id:'test-user',display_name:'测试创作者',csrf_token:'test-csrf'};else if(suffix==='/projects')data={items:projects};else if(suffix===`/projects/${project.id}`&&req.method==='DELETE'){projects=[];data={deleted:true,project_id:project.id};}else if(suffix.endsWith('/conversations'))data={items:[conversation]};else if(suffix.endsWith('/history'))data={items:history};else if(suffix.endsWith('/actions'))data={cards:[]};else if(suffix.endsWith('/status'))data={tasks:[task],runs:[run],queue:[],artifacts:[artifact],...(disabledCostGates?{runtime_policy:{cost_gates_enabled:false}}:{})};else if(suffix.endsWith('/messages')){history.push({id:crypto.randomUUID(),role:'user',visibility:'conversation',sequence:history.length+1,content:{storage:'inline_text',text:body.text}});data={saved:true};}else if(suffix.endsWith('/config')&&req.method==='GET')data=config;else if(suffix.endsWith('/config'))data={id:'draft-id',version:2,scope_kind:'project',scope_key:null};else if(suffix.endsWith('/publish'))data={state:'published'};else if(suffix.endsWith('/records'))data={items:[record],next_cursor:null};else if(suffix.endsWith('/records/00000000-0000-4000-8000-000000000404')){res.statusCode=403;data={record_type:'model_call',error:{code:'forbidden',message:'无权读取测试记录'}};}else if(suffix.includes('/records/'))data=record;else if(suffix.includes('/versions/'))data={version:{id:'99999999-9999-4999-8999-999999999999',record_type:'artifact_version',artifact_id:artifact.id,version:2,content:{storage:'inline_json',value:{title:'雾港来信'}}},state:{confirmation_status:'unconfirmed',dependency_status:'valid',quality_status:'unchecked'},content:{title:'雾港来信'}};res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data));});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'chrome'});
try{const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',x=>errors.push(x.message));await page.goto(base);await page.getByRole('heading',{name:project.title}).waitFor();await page.getByText('已保存原作。我们先来确认故事中必须保留的人物关系。').waitFor();await page.getByText('故事前提：雾港中的兄妹寻找真相。').waitFor();assert.equal(await page.getByText('Step2 已生成草稿 v1，请查看后确认，或提出具体修改。').count(),0);assert.equal(await page.getByRole('button',{name:'查看原始 JSON'}).count(),0);assert.equal(await page.locator('.artifact-chip').count(),0);await page.getByLabel('对话内容').fill('<img src=x onerror="window.XSS=true"> 请保留灯塔。');await page.getByLabel('运行中消息处理方式').selectOption('queue');await page.getByRole('button',{name:'发送',exact:false}).click();await page.locator('.message.user').waitFor();assert.equal(await page.evaluate(()=>window.XSS),undefined);const sent=requests.find(x=>x.url.endsWith('/messages'));assert.equal(sent.body.mode,'queue');assert.equal(sent.headers['x-csrf-token'],'test-csrf');assert.match(sent.headers['idempotency-key'],/^[\da-f-]{36}$/);await page.getByRole('button',{name:'配置与运行数据'}).click();await page.locator('#tools-page').waitFor({state:'visible'});assert.equal(await page.locator('.sidebar').isVisible(),false);assert.equal(await page.locator('.main').isVisible(),false);assert.equal(await page.getByRole('tab',{name:'配置',exact:true}).getAttribute('aria-selected'),'true');
// Explicitly disabled costs hide the form fields without weakening other budgets.
await page.getByText('任务预算与恢复',{exact:true}).click();
const costField=page.locator('[data-config-path="task.max_cost.amount"]'),currencyField=page.locator('[data-config-path="task.max_cost.currency"]');
assert.equal(await costField.isVisible(),!disabledCostGates);assert.equal(await costField.isDisabled(),disabledCostGates);
assert.equal(await currencyField.isVisible(),!disabledCostGates);assert.equal(await currencyField.isDisabled(),disabledCostGates);
assert.equal(await page.locator('[data-config-path="task.max_active_seconds"]').isVisible(),true);
assert.equal(await page.locator('[data-config-path="task.max_active_seconds"]').isDisabled(),false);
assert.equal(await page.locator('[data-config-path="context.input_token_cap"]').isDisabled(),false);
assert.equal(await page.locator('#cost-policy-notice').isVisible(),disabledCostGates);
if(disabledCostGates){
  assert.match(await page.locator('#cost-policy-notice').innerText(),/测试版已暂停费用门禁；费用统计仍保留。/);
  assert.equal(await page.locator('[data-action="config-inherit"][data-path="task.max_cost.amount"]').isVisible(),false);
  await page.getByText('全部配置 JSON',{exact:true}).click();
  const original=await page.locator('#config-json').inputValue(),changed=JSON.parse(original);changed.task.max_cost.amount='999';
  await page.locator('#config-json').fill(JSON.stringify(changed));await page.getByRole('button',{name:'应用 JSON 到表单',exact:true}).click();
  assert.equal(JSON.parse(await page.locator('#config-json').inputValue()).task.max_cost.amount,'999');
  assert.equal(await costField.isVisible(),false);
  await page.getByText('全部配置 JSON',{exact:true}).click();
  assert.equal(requests.filter(x=>x.url.endsWith('/account/config')&&x.method==='POST').length,0);
  await page.locator('#config-json').fill(original);await page.getByRole('button',{name:'应用 JSON 到表单',exact:true}).click();
}
const modelField=page.locator('select[data-config-path="model.name"]'),effortField=page.locator('select[data-config-path="model.reasoning_effort"]');
assert.equal(await modelField.inputValue(),'gpt-5.6-sol');assert.equal(await effortField.inputValue(),'medium');
assert.deepEqual(await modelField.locator('option').evaluateAll(nodes=>nodes.map(n=>n.value)),['gpt-5.6-sol','gpt-5.6-luna','gpt-5-mini','gpt-5-nano']);
await effortField.selectOption('max');await modelField.selectOption('gpt-5-mini');
assert.equal(await effortField.inputValue(),'medium');assert.deepEqual(await effortField.locator('option').evaluateAll(nodes=>nodes.map(n=>n.value)),['minimal','low','medium','high']);
assert.match(await page.locator('#budget-preview').innerText(),/400,000/);
assert.equal(JSON.parse(await page.locator('#config-json').inputValue()).model.reasoning_effort,'medium');
await effortField.selectOption('minimal');await modelField.selectOption('gpt-5-nano');assert.equal(await effortField.inputValue(),'minimal');
await modelField.selectOption('gpt-5.6-sol');assert.equal(await effortField.inputValue(),'medium');assert.equal(await effortField.locator('option[value=minimal]').count(),0);
assert.equal(requests.filter(x=>x.url.endsWith('/account/config')&&x.method==='POST').length,0);
await page.locator('[data-config-path="model.max_output_tokens"]').fill('9000');await page.getByRole('button',{name:'保存草稿',exact:true}).click();await page.getByRole('button',{name:'发布配置',exact:true}).click();await page.getByText('配置已发布，后续新运行生效').waitFor();const saved=requests.find(x=>x.url.endsWith('/account/config')&&x.method==='POST');assert.equal(saved.body.values.model.max_output_tokens,9000);assert.equal(saved.body.values.model.name,undefined);assert.equal(saved.body.values.model.reasoning_effort,undefined);await page.getByRole('tab',{name:'运行数据'}).click();assert.equal(await page.getByLabel('运行数据项目').inputValue(),project.id);await page.locator('.record-row').first().click();await page.getByRole('button',{name:'只读 JSON'}).click();assert.equal(await page.locator('#detail-body').getByText('DO-NOT-RENDER-THIS').count(),0);assert.match(await page.locator('#detail-body').innerText(),/已遮蔽/);assert.match(await page.locator('#detail-body').innerText(),/RateLimitError/);await page.locator('#detail-body summary').filter({hasText:'"estimated_cost"'}).click();assert.match(await page.locator('#detail-body').innerText(),/0\.125/);await page.screenshot({path:path.join(root,'tests/frontend-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(root,'tests/frontend-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'← 全部记录'}).click();await page.getByLabel('精确记录 ID').fill('00000000-0000-4000-8000-000000000404');await page.getByRole('button',{name:'筛选记录',exact:true}).click();await page.getByText('无权读取测试记录',{exact:true}).waitFor();assert.equal(await page.locator('#toast').innerText(),'无权读取测试记录');await page.getByRole('button',{name:'返回聊天工作区'}).click();assert.equal(await page.locator('.main').isVisible(),true);await page.getByRole('button',{name:`删除项目 ${project.title}`}).click();assert.equal(await page.locator('#modal-body input').count(),0);await page.getByRole('button',{name:'确认永久删除'}).click();await page.getByText('还没有项目').waitFor();const deletion=requests.find(x=>x.method==='DELETE'&&x.url.endsWith(`/projects/${project.id}`));assert.deepEqual(deletion.body,{confirm:true});assert.deepEqual(errors,[]);console.log(`Cost policy fixture: ${disabledCostGates?'disabled':'legacy absent'}`);console.log('PASS: account-global full-screen config, project-filtered runtime data, permanent delete confirmation, message mode, config publish, error rendering, redaction and responsive layout.');}finally{await browser.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
